/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UploadFileImport } from './routes/upload/file'
import { Route as UploadAnnouncementImport } from './routes/upload/announcement'
import { Route as CreateNexusImport } from './routes/create/nexus'
import { Route as CreateCoreImport } from './routes/create/core'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthLoginImport } from './routes/auth/login'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UploadFileRoute = UploadFileImport.update({
  path: '/upload/file',
  getParentRoute: () => rootRoute,
} as any)

const UploadAnnouncementRoute = UploadAnnouncementImport.update({
  path: '/upload/announcement',
  getParentRoute: () => rootRoute,
} as any)

const CreateNexusRoute = CreateNexusImport.update({
  path: '/create/nexus',
  getParentRoute: () => rootRoute,
} as any)

const CreateCoreRoute = CreateCoreImport.update({
  path: '/create/core',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/create/core': {
      id: '/create/core'
      path: '/create/core'
      fullPath: '/create/core'
      preLoaderRoute: typeof CreateCoreImport
      parentRoute: typeof rootRoute
    }
    '/create/nexus': {
      id: '/create/nexus'
      path: '/create/nexus'
      fullPath: '/create/nexus'
      preLoaderRoute: typeof CreateNexusImport
      parentRoute: typeof rootRoute
    }
    '/upload/announcement': {
      id: '/upload/announcement'
      path: '/upload/announcement'
      fullPath: '/upload/announcement'
      preLoaderRoute: typeof UploadAnnouncementImport
      parentRoute: typeof rootRoute
    }
    '/upload/file': {
      id: '/upload/file'
      path: '/upload/file'
      fullPath: '/upload/file'
      preLoaderRoute: typeof UploadFileImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthLoginRoute,
  AuthSignUpRoute,
  CreateCoreRoute,
  CreateNexusRoute,
  UploadAnnouncementRoute,
  UploadFileRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/login",
        "/auth/sign-up",
        "/create/core",
        "/create/nexus",
        "/upload/announcement",
        "/upload/file"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx"
    },
    "/create/core": {
      "filePath": "create/core.tsx"
    },
    "/create/nexus": {
      "filePath": "create/nexus.tsx"
    },
    "/upload/announcement": {
      "filePath": "upload/announcement.tsx"
    },
    "/upload/file": {
      "filePath": "upload/file.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
