services:
  client:
    build:
      context: client
    container_name: client
    env_file:
      - client/.env.docker
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - server

  server:
    build:
      context: server
    container_name: server
    env_file:
      - server/.env.docker
    ports:
      - 7000:7000
    networks:
      - app-network
    depends_on:
      - database
    command: sh -c "sleep 60 && echo "yo...what happened" && /app/main"
  
  database:
    image: surrealdb/surrealdb:v2.1.4
    container_name: database
    ports:
      - 8000:8000
    volumes:
      - ./server/database/data:/tmp/sdb/data
    networks:
      - app-network
    command: start --user root --pass root rocksdb:/tmp/sdb/data
    healthcheck:
      test: ["CMD", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge