services:
  client:
    build:
      context: client
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
    container_name: scholar-sync-client
    env_file:
      - client/.env.docker
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - server

  server:
    build:
      context: server
    container_name: scholar-sync-server
    env_file:
      - server/.env.docker
    ports:
      - 7000:7000
    networks:
      - app-network
    depends_on:
      surrealdb:
        condition: service_healthy
  
  surrealdb:
    image: surrealdb/surrealdb:v2.1.4-dev
    container_name: scholar-sync-surrealdb
    ports:
      - 8000:8000
    volumes:
      - ./server/database/data:/tmp/sdb/data
    networks:
      - app-network
    command: 
      - start
      - --user 
      - ${SURREALDB_USERNAME} 
      - --pass 
      - ${SURREALDB_PASSWORD}
      - rocksdb:/tmp/sdb/data
    healthcheck:
      test: ["CMD", "/surreal", "is-ready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge