scalar Upload

input SignUpData {
  fullName: String!
  email: String!
  password: String!
}

input CoreData {
  name: String!
  imageUrl: String!
}

input NexusData {
  name: String!
  category: String!
  coreId: String!
}

input FileData {
  title: String!
  description: String!
  upload: Upload!
  nexusId: String!
}

input AnnouncementData {
  title: String!
  message: String!
  nexusId: String!
}

input CoreMember {
  userId: String!
  coreId: String!
}

input NexusMember {
  userId: String!
  nexusId: String!
}

type Mutation {
  signUp(input: SignUpData!): String!

  createCore(input: CoreData!): ID!
  deleteCore(coreId: String!): Boolean!

  inviteMemberToCore(input: CoreMember!): Boolean!
  removeMemberFromCore(input: CoreMember!): Boolean!

  leaveCore(coreId: String!): Boolean!

  createNexus(input: NexusData!): ID!
  deleteNexus(nexusId: String!): Boolean!

  inviteMemberToNexus(input: NexusMember!): Boolean!
  removeMemberFromNexus(input: NexusMember!): Boolean!

  leaveNexus(nexusId: String!): Boolean!

  createAnnouncement(input: AnnouncementData!): ID!

  createFile(input: FileData!): ID!
}
