scalar Upload

input SignUpData {
  fullName: String!
  email: String!
  password: String!
}

input CoreData {
  name: String!
}

type Mutation {
  signUpUser(input: SignUpData!): String!
  singleUpload(file: Upload!): Boolean!
  createCore(input: CoreData!): ID!
}
