input LoginData {
  email: String!
  password: String!
}

input GetNexusData {
  core: String!
}

type Query {
  loginUser(input: LoginData!): String!
  getUser: Profile!
  getCores: [Core]!
  getNexus(input: GetNexusData): [Nexus]!
}
