input LoginData {
  email: String!
  password: String!
}

input GetNexusData {
  core: String!
}

type Query {
  login(input: LoginData!): String!
  logout: Boolean!

  getUser: Profile!
  getUserData: [Core]!
}
