scalar Time

enum ProfileType {
  ADMIN
  PSEUDOADMIN
  NORMAL
}

type Profile {
  id: ID!
  fullName: String!
  email: String!
  profileType: ProfileType!
  createdAt: Time!
}

type Core {
  id: ID!
  name: String!
  creator: Profile!
  nexus: [Nexus]!
  createdAt: Time!
  updatedAt: Time!
}

type Nexus {
  id: ID!
  name: String!
  core: Core!
  creator: Profile!
  files: [File]!
  announcements: [Announcement]!
  createdAt: Time!
  updatedAt: Time!
}

type File {
  id: ID!
  title: String!
  fileUrl: String!
  sentBy: Profile!
  nexus: Nexus!
  timeStamp: Time!
}

type Announcement {
  id: ID!
  nexus: Nexus!
  title: String!
  message: String!
  sentBy: Profile!
  timeStamp: Time!
}
