scalar Time

enum ProfileType {
  ADMIN
  PSEUDOADMIN
  NORMAL
}

type Profile {
  id: ID!
  fullName: String!
  email: String!
  userType: ProfileType!
  createdAt: Time!
}

type Core {
  id: ID!
  name: String!
  imageUrl: String!
  creator: Profile!
  nexus: [Nexus]!
  createdAt: Time!
  updatedAt: Time!
}

type Nexus {
  id: ID!
  name: String!
  category: String!
  creator: Profile!
  users: [Profile]!
  files: [File]!
  announcements: [Announcement]!
  createdAt: Time!
  updatedAt: Time!
}

type File {
  id: ID!
  title: String!
  description: String
  fileUrl: String!
  sentBy: Profile!
  timeStamp: Time!
}

type Announcement {
  id: ID!
  title: String!
  message: String!
  sentBy: Profile!
  timeStamp: Time!
}
