package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"

	"github.com/soorya-u/scholar-sync/generated"
	"github.com/soorya-u/scholar-sync/models"
)

func (r *announcementResolver) SentBy(ctx context.Context, obj *models.Announcement) (*models.Profile, error) {
	return obj.SentBy, nil
}

func (r *coreResolver) Nexus(ctx context.Context, obj *models.Core) ([]*models.Nexus, error) {
	return obj.Nexus, nil
}

func (r *fileResolver) SentBy(ctx context.Context, obj *models.File) (*models.Profile, error) {
	return obj.SentBy, nil
}

func (r *nexusResolver) Files(ctx context.Context, obj *models.Nexus) ([]*models.File, error) {
	return obj.Files, nil
}

func (r *nexusResolver) Announcements(ctx context.Context, obj *models.Nexus) ([]*models.Announcement, error) {
	return obj.Announcements, nil
}

func (r *Resolver) Announcement() generated.AnnouncementResolver { return &announcementResolver{r} }

func (r *Resolver) Core() generated.CoreResolver { return &coreResolver{r} }

func (r *Resolver) File() generated.FileResolver { return &fileResolver{r} }

func (r *Resolver) Nexus() generated.NexusResolver { return &nexusResolver{r} }

type announcementResolver struct{ *Resolver }
type coreResolver struct{ *Resolver }
type fileResolver struct{ *Resolver }
type nexusResolver struct{ *Resolver }
