mutation CreateCore($name: String!, $imageUrl: String!) {
  createCore(input: { name: $name, imageUrl: $imageUrl })
}

mutation DeleteCore($coreId: String!) {
  deleteCore(coreId: $coreId)
}

mutation InviteMemberToCore($coreId: String!, $userId: String!) {
  inviteMemberToCore(input: { coreId: $coreId, userId: $userId })
}

mutation RemoveMemberFromCore($coreId: String!, $userId: String!) {
  removeMemberFromCore(input: { coreId: $coreId, userId: $userId })
}

mutation LeaveCore($coreId: String!) {
  leaveCore(coreId: $coreId)
}
