mutation CreateFile(
  $title: String!
  $description: String!
  $upload: Upload!
  $nexusId: String!
) {
  createFile(
    input: {
      title: $title
      description: $description
      upload: $upload
      nexusId: $nexusId
    }
  )
}
