mutation CreateNexus($name: String!, $category: String!, $coreId: String!) {
  createNexus(input: { name: $name, category: $category, coreId: $coreId })
}

mutation DeleteNexus($nexusId: String!) {
  deleteNexus(nexusId: $nexusId)
}

mutation InviteMemberToNexus($userId: String!, $nexusId: String!) {
  inviteMemberToNexus(input: { userId: $userId, nexusId: $nexusId })
}

mutation RemoveMemberFromNexus($userId: String!, $nexusId: String!) {
  removeMemberFromNexus(input: { userId: $userId, nexusId: $nexusId })
}

mutation LeaveNexus($nexusId: String!) {
  leaveNexus(nexusId: $nexusId)
}