query GetCurrentUser {
  getUser {
    id
    fullName
    email
    createdAt
  }
}

query GetTree {
  getTree {
    id
    name
    imageUrl
    nexus {
      id
      name
      category
    }
  }
}
